# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from pathlib import Path

import ruamel.yaml
from hatchling.metadata.plugin.interface import MetadataHookInterface

yaml = ruamel.yaml.YAML(typ="safe")


class VersionYamlHook(MetadataHookInterface):
    """Hatch metadata hook that reads version from VERSION.yaml."""

    def update(self, metadata: dict) -> None:
        version_path = Path(self.root) / "VERSION.yaml"
        if not version_path.exists():
            raise FileNotFoundError(
                f"VERSION.yaml not found at {version_path}. "
                "This file should have been generated by wt-compiler."
            )
        data = yaml.load(version_path)
        try:
            metadata["version"] = f"{data['MAJ']}.{data['MIN']}.{data.get('PATCH', 0)}"
        except (TypeError, KeyError) as e:
            raise ValueError(
                f"VERSION.yaml at {version_path} is malformed: "
                f"expected a mapping with MAJ and MIN keys. Got: {data!r}"
            ) from e
