[workspace]
platforms = ['linux-64', 'osx-arm64', 'osx-64', 'win-64']

name = "wwf-traffic"
channels = [
  'https://repo.prefix.dev/ecoscope-workflows/',
  'https://repo.prefix.dev/ecoscope-workflows-custom/',
  'conda-forge',
]

[dependencies]
wt-compiler = ">=0.8.2, <0.9"
graphviz = "*"
go-yq = "*"
