# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    apply_arithmetic_operation as apply_arithmetic_operation,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import (
    draw_time_series_bar_chart as draw_time_series_bar_chart,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import (
    any_keyed_iterables_are_skips as any_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_numeric as convert_column_values_to_numeric,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map_1
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    decompose_datetime as decompose_datetime,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_ste.tasks.io import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    envelope_gdf as envelope_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    spatial_join as spatial_join,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    add_mapped_column_value as add_mapped_column_value,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    subset_columns as subset_columns,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.io import (
    load_and_merge_csvs as load_and_merge_csvs,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.results import (
    create_period_comparison_widget as create_period_comparison_widget,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.results import (
    get_top_category as get_top_category,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    add_ratio_column as add_ratio_column,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    aggregate_by as aggregate_by,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    apply_cmap as apply_cmap,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    df_to_point_gdf as df_to_point_gdf,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    extract_trade_route as extract_trade_route,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    safe_divide as safe_divide,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    set_color_palette as set_color_palette,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    configure_base_maps = (
        task(set_base_maps_pydeck)
        .validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("configure_base_maps") or {}))
        .call()
    )

    load_traffic_csvs = (
        task(load_and_merge_csvs)
        .validate()
        .set_task_instance_id("load_traffic_csvs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(on="Report ID", **(params.get("load_traffic_csvs") or {}))
        .call()
    )

    map_necessary_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_necessary_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=load_traffic_csvs,
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[
                "Report ID",
                "Category of Incident_x",
                "Country of Incident_x",
                "Date of Incident_x",
                "Full Scientific Name",
                "Item / Commodity Type",
                "Count",
                "Weight",
                "Unit of Weight",
                "Kingdom",
                "Phylum",
                "Class",
                "Order",
                "Family",
                "Common Name",
                "Role",
                "Order in Trade Route",
                "Country",
                "Latitude",
                "Longitude",
                "Outcome",
                "Number of People Arrested",
                "Number of People Charged",
                "Number of People Fined",
                "Number of People Imprisoned",
            ],
            rename_columns={
                "Report ID": "report_id",
                "Category of Incident_x": "category_of_incident",
                "Country of Incident_x": "country_of_incident",
                "Date of Incident_x": "date_of_incident",
                "Full Scientific Name": "full_scientific_name",
                "Item / Commodity Type": "commodity_type",
                "Count": "count",
                "Weight": "weight",
                "Unit of Weight": "unit_of_weight",
                "Kingdom": "kingdom",
                "Phylum": "phylum",
                "Class": "class",
                "Order": "order",
                "Family": "family",
                "Common Name": "common_name",
                "Role": "role",
                "Order in Trade Route": "order_in_trade_route",
                "Country": "country",
                "Latitude": "latitude",
                "Longitude": "longitude",
                "Outcome": "outcome",
                "Number of People Arrested": "no_of_people_arrested",
                "Number of People Charged": "no_of_people_charged",
                "Number of People Fined": "no_of_people_fined",
                "Number of People Imprisoned": "no_of_people_imprisoned",
            },
            **(params.get("map_necessary_columns") or {}),
        )
        .call()
    )

    single_value_routes = (
        task(extract_trade_route)
        .validate()
        .set_task_instance_id("single_value_routes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_necessary_columns,
            route_roles=["Origin Location", "Transit Location", "Destination Location"],
            key=["report_id", "full_scientific_name", "commodity_type"],
            role_column="role",
            order_column="order_in_trade_route",
            **(params.get("single_value_routes") or {}),
        )
        .call()
    )

    objects_to_numeric = (
        task(convert_column_values_to_numeric)
        .validate()
        .set_task_instance_id("objects_to_numeric")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=single_value_routes,
            columns=[
                "count",
                "weight",
                "no_of_people_arrested",
                "no_of_people_charged",
                "no_of_people_fined",
                "no_of_people_imprisoned",
                "latitude",
                "longitude",
            ],
            **(params.get("objects_to_numeric") or {}),
        )
        .call()
    )

    df_gdf = (
        task(df_to_point_gdf)
        .validate()
        .set_task_instance_id("df_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=objects_to_numeric,
            latitude_column="latitude",
            longitude_column="longitude",
            crs="EPSG:4326",
            **(params.get("df_gdf") or {}),
        )
        .call()
    )

    download_gvl_buffer = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("download_gvl_buffer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/nmp88q0hc1163b0i19htg/gvl_30km_buffer.parquet?rlkey=n13oii61yr13vznqjjp5b4ujh&st=7hf9951w&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=True,
            retries=3,
            unzip=False,
            **(params.get("download_gvl_buffer") or {}),
        )
        .call()
    )

    load_gvl_gdf = (
        task(load_df)
        .validate()
        .set_task_instance_id("load_gvl_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=download_gvl_buffer,
            layer=None,
            deserialize_json=False,
            **(params.get("load_gvl_gdf") or {}),
        )
        .call()
    )

    reproject_gvl = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("reproject_gvl")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=load_gvl_gdf,
            target_crs="EPSG:4326",
            **(params.get("reproject_gvl") or {}),
        )
        .call()
    )

    spatial_join_gvl = (
        task(spatial_join)
        .validate()
        .set_task_instance_id("spatial_join_gvl")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left_df=df_gdf,
            right_df=reproject_gvl,
            how="inner",
            predicate="within",
            **(params.get("spatial_join_gvl") or {}),
        )
        .call()
    )

    retain_gvl_countries = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("retain_gvl_countries")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=spatial_join_gvl,
            column="country_of_incident",
            values=["Rwanda", "Uganda", "Congo, Democratic Republic of The"],
            **(params.get("retain_gvl_countries") or {}),
        )
        .call()
    )

    map_species = (
        task(add_mapped_column_value)
        .validate()
        .set_task_instance_id("map_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=retain_gvl_countries,
            column="full_scientific_name",
            mapping={
                "Elephantidae": "Elephant",
                "Loxodonta": "Elephant",
                "Hippopotamidae": "Hippo",
                "Hippopotamus": "Hippo",
                "Hippopotamus amphibius": "Hippo",
                "Gorilla beringei": "Gorilla",
                "Gorilla beringei beringei": "Gorilla",
                "Pan troglodytes": "Chimpanzee",
                "Panthera leo": "Lion",
                "Manidae": "Pangolin",
                "Cercopithecus kandti": "Golden monkey",
                "Phacochoerus africanus": "Warthog",
                "Psittacus erithacus": "Grey parrot",
                "Poicephalus robustus fuscicollis": "Brown-necked parrot",
                "Gyps africanus": "White-backed vulture",
                "Trigonoceps occipitalis": "White-headed vulture",
                "Testudinidae": "Tortoises",
                "Bovidae": "Bovids",
            },
            new_column="common_group",
            default=None,
            keep_unmapped=True,
            **(params.get("map_species") or {}),
        )
        .call()
    )

    map_incident_category = (
        task(add_mapped_column_value)
        .validate()
        .set_task_instance_id("map_incident_category")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_species,
            column="category_of_incident",
            mapping={
                "1. Seizure": "Seizure",
                "2. Poaching / Illegal Harvesting": "Poaching",
                "3. Smuggling / Illegal Trade (not elsewhere included)": "Smuggling",
                "6. Human-Wildlife Conflict": "Human-Wildlife Conflict",
                "9. Enforcement Action / Prosecution": "Enforcement",
            },
            new_column="incident_category",
            default=None,
            keep_unmapped=True,
            **(params.get("map_incident_category") or {}),
        )
        .call()
    )

    add_df_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("add_df_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_incident_category,
            time_col="date_of_incident",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("add_df_temporal_index") or {}),
        )
        .call()
    )

    decompose_dai_datetime = (
        task(decompose_datetime)
        .validate()
        .set_task_instance_id("decompose_dai_datetime")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_df_temporal_index,
            datetime_column="date_of_incident",
            components=["year", "month"],
            remove_source=False,
            column_prefix="incident",
            **(params.get("decompose_dai_datetime") or {}),
        )
        .call()
    )

    incident_species_colormap = (
        task(set_color_palette)
        .validate()
        .set_task_instance_id("incident_species_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("incident_species_colormap") or {}))
        .call()
    )

    cmap_incidents = (
        task(apply_cmap)
        .validate()
        .set_task_instance_id("cmap_incidents")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=decompose_dai_datetime,
            input_column_name="category_of_incident",
            color_palette=incident_species_colormap,
            output_column_name="incident_colors",
            color_format="rgba_tuple",
            alpha=1.0,
            **(params.get("cmap_incidents") or {}),
        )
        .call()
    )

    cmap_species = (
        task(apply_cmap)
        .validate()
        .set_task_instance_id("cmap_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=cmap_incidents,
            input_column_name="common_group",
            color_palette=incident_species_colormap,
            output_column_name="species_colors",
            color_format="rgba_tuple",
            alpha=1.0,
            **(params.get("cmap_species") or {}),
        )
        .call()
    )

    split_events_by_group = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_events_by_group")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=cmap_species,
            groupers=groupers,
            **(params.get("split_events_by_group") or {}),
        )
        .call()
    )

    incidents_per_year = (
        task(aggregate_by)
        .validate()
        .set_task_instance_id("incidents_per_year")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col=["incident_year"],
            agg_col="report_id",
            agg_func="count",
            agg_col_name="no_of_incidents",
            add_percent=False,
            pct_col_name=None,
            decimals=1,
            sort=None,
            **(params.get("incidents_per_year") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    incidents_species_year = (
        task(aggregate_by)
        .validate()
        .set_task_instance_id("incidents_species_year")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col=["incident_year", "common_group"],
            agg_col="report_id",
            agg_func="count",
            agg_col_name="no_of_incidents",
            add_percent=False,
            pct_col_name=None,
            decimals=1,
            sort=None,
            **(params.get("incidents_species_year") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    total_arrested = (
        task(aggregate_by)
        .validate()
        .set_task_instance_id("total_arrested")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col=["incident_year"],
            agg_col="no_of_people_arrested",
            agg_func="sum",
            agg_col_name="no_of_people_arrested",
            add_percent=False,
            pct_col_name=None,
            decimals=1,
            sort=None,
            **(params.get("total_arrested") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    total_imprisoned = (
        task(aggregate_by)
        .validate()
        .set_task_instance_id("total_imprisoned")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col=["incident_year"],
            agg_col="no_of_people_imprisoned",
            agg_func="sum",
            agg_col_name="no_of_people_imprisoned",
            add_percent=False,
            pct_col_name=None,
            decimals=1,
            sort=None,
            **(params.get("total_imprisoned") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    zip_total_arrested_imprisoned = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_total_arrested_imprisoned")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[total_arrested, total_imprisoned],
            **(params.get("zip_total_arrested_imprisoned") or {}),
        )
        .call()
    )

    merge_arrested_imprisoned = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("merge_arrested_imprisoned")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            on="incident_year",
            how="inner",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("merge_arrested_imprisoned") or {}),
        )
        .mapvalues(argnames=["left", "right"], argvalues=zip_total_arrested_imprisoned)
    )

    add_conviction_rate = (
        task(add_ratio_column)
        .validate()
        .set_task_instance_id("add_conviction_rate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            numerator_col="no_of_people_imprisoned",
            denominator_col="no_of_people_arrested",
            ratio_col_name="conviction_rate",
            as_percent=True,
            fill_invalid=0.0,
            decimals=1,
            **(params.get("add_conviction_rate") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=merge_arrested_imprisoned)
    )

    filter_ivory = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("filter_ivory")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="commodity_type",
            values=["Ivory Pieces - Raw", "Ivory - Worked", "Tusk"],
            **(params.get("filter_ivory") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    ivory_weight_per_year = (
        task(aggregate_by)
        .validate()
        .set_task_instance_id("ivory_weight_per_year")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col=["incident_year"],
            agg_col="weight",
            agg_func="sum",
            agg_col_name="total_seizure_of_ivory",
            add_percent=False,
            pct_col_name=None,
            decimals=1,
            sort=None,
            **(params.get("ivory_weight_per_year") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=filter_ivory)
    )

    ts_species_chart = (
        task(draw_time_series_bar_chart)
        .validate()
        .set_task_instance_id("ts_species_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="date_of_incident",
            y_axis="report_id",
            category="common_group",
            agg_function="count",
            time_interval="year",
            color_column="species_colors",
            plot_style=None,
            layout_style=None,
            **(params.get("ts_species_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    incidents_bar_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("incidents_bar_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="incidents_by_species",
            **(params.get("incidents_bar_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ts_species_chart)
    )

    ts_category_chart = (
        task(draw_time_series_bar_chart)
        .validate()
        .set_task_instance_id("ts_category_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            x_axis="date_of_incident",
            y_axis="report_id",
            category="incident_category",
            agg_function="count",
            time_interval="year",
            color_column="species_colors",
            plot_style=None,
            layout_style=None,
            **(params.get("ts_category_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=split_events_by_group)
    )

    category_bar_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("category_bar_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="incidents_by_category",
            **(params.get("category_bar_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ts_category_chart)
    )

    create_gvl_boundary = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("create_gvl_boundary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "filled": False,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": None,
                "get_line_color": [0, 0, 0],
                "opacity": 0.45,
                "get_line_width": 1.55,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            geodataframe=reproject_gvl,
            legend={
                "values": [{"label": "GVL Overlay 30kms", "color": "#000000"}],
                "title": "Boundaries",
            },
            **(params.get("create_gvl_boundary") or {}),
        )
        .call()
    )

    create_incidents_layer = (
        task(create_scatterplot_layer_1)
        .validate()
        .set_task_instance_id("create_incidents_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": "incident_colors",
                "get_line_color": "incident_colors",
                "get_radius": 2.35,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Incidents",
                "label_column": "incident_category",
                "color_column": "incident_colors",
                "sort": "ascending",
            },
            data_url=None,
            **(params.get("create_incidents_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_events_by_group)
    )

    create_species_layer = (
        task(create_scatterplot_layer_1)
        .validate()
        .set_task_instance_id("create_species_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": "species_colors",
                "get_line_color": "species_colors",
                "get_radius": 2.35,
                "opacity": 0.75,
                "stroked": True,
            },
            legend={
                "title": "Incidents",
                "label_column": "common_group",
                "color_column": "species_colors",
                "sort": "ascending",
            },
            data_url=None,
            **(params.get("create_species_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_events_by_group)
    )

    zoom_to_envelope = (
        task(envelope_gdf)
        .validate()
        .set_task_instance_id("zoom_to_envelope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("zoom_to_envelope") or {}))
        .mapvalues(argnames=["gdf"], argvalues=split_events_by_group)
    )

    gdf_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("gdf_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0, bearing=0, max_zoom=12, **(params.get("gdf_image_extent") or {})
        )
        .mapvalues(argnames=["gdf"], argvalues=zoom_to_envelope)
    )

    combined_gvl_incident_layers = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combined_gvl_incident_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=create_gvl_boundary,
            **(params.get("combined_gvl_incident_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=create_incidents_layer)
    )

    combined_gvl_species_layers = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combined_gvl_species_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=create_gvl_boundary,
            **(params.get("combined_gvl_species_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=create_species_layer)
    )

    zip_incidents_with_viewstate = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_incidents_with_viewstate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combined_gvl_incident_layers, gdf_image_extent],
            **(params.get("zip_incidents_with_viewstate") or {}),
        )
        .call()
    )

    zip_species_with_viewstate = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_species_with_viewstate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combined_gvl_species_layers, gdf_image_extent],
            **(params.get("zip_species_with_viewstate") or {}),
        )
        .call()
    )

    draw_incidents_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_incidents_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            **(params.get("draw_incidents_map") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"],
            argvalues=zip_incidents_with_viewstate,
        )
    )

    draw_species_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_species_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=10,
            legend_style={"placement": "bottom-right"},
            **(params.get("draw_species_map") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=zip_species_with_viewstate
        )
    )

    incidents_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("incidents_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="incidents_by_category",
            **(params.get("incidents_map_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_incidents_map)
    )

    species_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("species_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="incidents_by_species",
            **(params.get("species_map_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_species_map)
    )

    subset_traffic_columns = (
        task(subset_columns)
        .validate()
        .set_task_instance_id("subset_traffic_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["date_of_incident", "incident_category", "role", "common_group"],
            exclude=None,
            strict=False,
            **(params.get("subset_traffic_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    filtered_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("filtered_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Summary table of incidents",
            **(params.get("filtered_table_html") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=subset_traffic_columns)
    )

    filtered_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("filtered_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="summary_table_of_incidents",
            **(params.get("filtered_table_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=filtered_table_html)
    )

    widget_incidents_map = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("widget_incidents_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(title="Incidents Map", **(params.get("widget_incidents_map") or {}))
        .map(argnames=["view", "data"], argvalues=incidents_map_html)
    )

    widget_incidents_map_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_incidents_map_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_incidents_map,
            **(params.get("widget_incidents_map_grouped") or {}),
        )
        .call()
    )

    widget_species_map = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("widget_species_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(title="Species Map", **(params.get("widget_species_map") or {}))
        .map(argnames=["view", "data"], argvalues=species_map_html)
    )

    widget_species_map_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_species_map_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_species_map,
            **(params.get("widget_species_map_grouped") or {}),
        )
        .call()
    )

    widget_incidents_species_chart = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("widget_incidents_species_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Incidents by Species Over Time",
            **(params.get("widget_incidents_species_chart") or {}),
        )
        .map(argnames=["view", "data"], argvalues=incidents_bar_html)
    )

    species_chart_widget_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("species_chart_widget_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_incidents_species_chart,
            **(params.get("species_chart_widget_grouped") or {}),
        )
        .call()
    )

    widget_incidents_category_chart = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("widget_incidents_category_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Incidents by Category Over Time",
            **(params.get("widget_incidents_category_chart") or {}),
        )
        .map(argnames=["view", "data"], argvalues=category_bar_html)
    )

    category_chart_widget_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("category_chart_widget_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_incidents_category_chart,
            **(params.get("category_chart_widget_grouped") or {}),
        )
        .call()
    )

    widget_summary_table = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("widget_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Summary Table of Incidents",
            **(params.get("widget_summary_table") or {}),
        )
        .map(argnames=["view", "data"], argvalues=filtered_table_html_url)
    )

    widget_summary_table_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_summary_table_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_summary_table,
            **(params.get("widget_summary_table_grouped") or {}),
        )
        .call()
    )

    total_incidents_sum = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_incidents_sum")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="no_of_incidents", **(params.get("total_incidents_sum") or {})
        )
        .mapvalues(argnames=["df"], argvalues=incidents_per_year)
    )

    widget_total_incidents = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_total_incidents")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Number of Incidents",
            decimal_places=0,
            **(params.get("widget_total_incidents") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_incidents_sum)
    )

    widget_total_incidents_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_total_incidents_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_total_incidents,
            **(params.get("widget_total_incidents_grouped") or {}),
        )
        .call()
    )

    widget_incidents_yoy = (
        task(create_period_comparison_widget)
        .validate()
        .set_task_instance_id("widget_incidents_yoy")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Incidents This Year vs Last Year",
            period_col="incident_year",
            value_col="no_of_incidents",
            decimal_places=0,
            current_period=None,
            **(params.get("widget_incidents_yoy") or {}),
        )
        .map(argnames=["view", "df"], argvalues=incidents_per_year)
    )

    widget_incidents_yoy_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_incidents_yoy_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_incidents_yoy,
            **(params.get("widget_incidents_yoy_grouped") or {}),
        )
        .call()
    )

    species_totals = (
        task(aggregate_by)
        .validate()
        .set_task_instance_id("species_totals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            group_col=["common_group"],
            agg_col="report_id",
            agg_func="count",
            agg_col_name="no_of_incidents",
            add_percent=False,
            pct_col_name=None,
            decimals=1,
            sort=None,
            **(params.get("species_totals") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_events_by_group)
    )

    top_species_label = (
        task(get_top_category)
        .validate()
        .set_task_instance_id("top_species_label")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            category_col="common_group",
            value_col="no_of_incidents",
            suffix=" incidents",
            **(params.get("top_species_label") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=species_totals)
    )

    widget_top_species = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_top_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Most Frequently Trafficked Flagship Species",
            **(params.get("widget_top_species") or {}),
        )
        .map(argnames=["view", "data"], argvalues=top_species_label)
    )

    widget_top_species_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_top_species_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_top_species,
            **(params.get("widget_top_species_grouped") or {}),
        )
        .call()
    )

    total_arrested_sum = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_arrested_sum")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="no_of_people_arrested",
            **(params.get("total_arrested_sum") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=total_arrested)
    )

    widget_total_arrested = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_total_arrested")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Suspects Arrested",
            decimal_places=0,
            **(params.get("widget_total_arrested") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_arrested_sum)
    )

    widget_total_arrested_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_total_arrested_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_total_arrested,
            **(params.get("widget_total_arrested_grouped") or {}),
        )
        .call()
    )

    total_convicted_sum = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_convicted_sum")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="no_of_people_imprisoned",
            **(params.get("total_convicted_sum") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=total_imprisoned)
    )

    widget_total_convicted = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_total_convicted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Suspects Convicted",
            decimal_places=0,
            **(params.get("widget_total_convicted") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_convicted_sum)
    )

    widget_total_convicted_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_total_convicted_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_total_convicted,
            **(params.get("widget_total_convicted_grouped") or {}),
        )
        .call()
    )

    zip_arrested_convicted_sums = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_arrested_convicted_sums")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[total_convicted_sum, total_arrested_sum],
            **(params.get("zip_arrested_convicted_sums") or {}),
        )
        .call()
    )

    conviction_ratio = (
        task(safe_divide)
        .validate()
        .set_task_instance_id("conviction_ratio")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(fill_invalid=0.0, **(params.get("conviction_ratio") or {}))
        .mapvalues(argnames=["a", "b"], argvalues=zip_arrested_convicted_sums)
    )

    conviction_rate_pct = (
        task(apply_arithmetic_operation)
        .validate()
        .set_task_instance_id("conviction_rate_pct")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            b=100, operation="multiply", **(params.get("conviction_rate_pct") or {})
        )
        .mapvalues(argnames=["a"], argvalues=conviction_ratio)
    )

    widget_conviction_rate = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_conviction_rate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Conviction Rate",
            decimal_places=1,
            **(params.get("widget_conviction_rate") or {}),
        )
        .map(argnames=["view", "data"], argvalues=conviction_rate_pct)
    )

    widget_conviction_rate_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_conviction_rate_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_conviction_rate,
            **(params.get("widget_conviction_rate_grouped") or {}),
        )
        .call()
    )

    total_ivory_sum = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_ivory_sum")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="total_seizure_of_ivory",
            **(params.get("total_ivory_sum") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ivory_weight_per_year)
    )

    widget_total_ivory = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("widget_total_ivory")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Seizures of Ivory (kg)",
            decimal_places=1,
            **(params.get("widget_total_ivory") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_ivory_sum)
    )

    widget_total_ivory_grouped = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("widget_total_ivory_grouped")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=widget_total_ivory,
            **(params.get("widget_total_ivory_grouped") or {}),
        )
        .call()
    )

    wwf_traffic_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("wwf_traffic_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                widget_total_incidents_grouped,
                widget_incidents_yoy_grouped,
                widget_top_species_grouped,
                widget_total_arrested_grouped,
                widget_total_convicted_grouped,
                widget_conviction_rate_grouped,
                widget_total_ivory_grouped,
                widget_incidents_map_grouped,
                widget_species_map_grouped,
                species_chart_widget_grouped,
                category_chart_widget_grouped,
                widget_summary_table_grouped,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("wwf_traffic_dashboard") or {}),
        )
        .call()
    )

    return wwf_traffic_dashboard
