# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from unittest.mock import patch

import jsonschema
import pytest
from ecoscope_workflows_wwf_traffic_workflow.metadata import (
    load_params_schema,
    load_rjsf_schema,
)
from fastapi.testclient import TestClient
from wt_contracts import params_to_formdata as _params_to_formdata
from wt_runner.app import app
from wt_runner.testing import Case


@pytest.fixture
def client(matchspec_override: str):
    with patch.dict(
        "os.environ",
        {"ECOSCOPE_WORKFLOWS_MATCHSPEC_OVERRIDE": matchspec_override},
    ):
        with TestClient(app) as client:
            yield client


@pytest.fixture(scope="session")
def formdata(success_case: Case) -> dict:
    """Build the nested formdata representation from flat success-case params.

    Walks the rjsf schema's top-level properties to discriminate flat keys
    (kept as-is) from task-group keys (used to nest the matching members).
    """
    return _params_to_formdata(
        success_case.params, load_rjsf_schema(), load_params_schema()
    )


def test_get_params(client: TestClient):
    response = client.get("/rjsf")
    assert response.status_code == 200
    assert set(list(response.json())) == {
        "properties",
        "$defs",
        "additionalProperties",
        "uiSchema",
    }


def test_get_data_connection_property_names(client: TestClient):
    response = client.get("/data-connection-property-names")
    assert response.status_code == 200
    response_json = response.json()
    assert isinstance(response_json, dict)
    assert all(
        isinstance(k, str) and isinstance(v, list) for k, v in response_json.items()
    )


def test_validate_formdata(client: TestClient, success_case: Case, formdata: dict):
    invalid_request = client.post("/formdata-to-params", json={"invalid": "request"})
    assert invalid_request.status_code == 422

    response = client.post("/formdata-to-params", json=formdata)
    assert response.status_code == 200

    assert set(success_case.params).issubset(set(response.json()))

    if set(formdata) != set(success_case.params):
        # this workflow uses task groups, so verify formdata fails the flat
        # params schema (since task groups aren't valid top-level params keys)
        with pytest.raises(jsonschema.ValidationError):
            jsonschema.validate(formdata, load_params_schema())

    assert response.json() == success_case.params


def test_generate_nested_params(client: TestClient, success_case: Case, formdata: dict):
    response = client.post("/params-to-formdata", json=success_case.params)
    assert response.status_code == 200

    assert response.json() == formdata


def test_round_trip(client: TestClient, success_case: Case, formdata: dict):
    generate_params_response = client.post(
        "/params-to-formdata", json=success_case.params
    )
    assert generate_params_response.status_code == 200
    assert generate_params_response.json() == formdata

    validate_response = client.post(
        "/formdata-to-params", json=generate_params_response.json()
    )
    assert validate_response.status_code == 200

    assert validate_response.json() == success_case.params
