# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


import json
import os
import sys
from importlib.metadata import PackageNotFoundError, version
from io import TextIOWrapper
from pathlib import Path
from typing import Any, Optional
from urllib.parse import urlparse

import click

RELEASE_NAME = "ecoscope-workflows-wwf-traffic-workflow"


@click.group()
def cli() -> None:
    pass


@cli.command()
@click.option(
    "--config-file",
    type=click.File("r"),
    required=False,
    help="Configuration parameters for running the workflow.",
)
@click.option(
    "--config-json",
    type=str,
    required=False,
    help="JSON string of configuration parameters for running the workflow.",
)
@click.option(
    "--execution-mode",
    required=True,
    type=click.Choice(["sequential"]),
)
@click.option(
    "--mock-io/--no-mock-io",
    is_flag=True,
    default=False,
    help="Whether or not to mock io with 3rd party services; for testing only.",
)
@click.option(
    "--otel-exporter",
    type=click.Choice(["console", "gcp"]),
    required=False,
    default=None,
    help=(
        "OpenTelemetry exporter backend. Options: gcp (Google Cloud Trace), console (for testing/development). "
        "Leave unset to disable export of traces."
    ),
)
@click.option(
    "--otel-console-exporter-dst",
    type=click.Choice(["stdout", "file"]),
    required=False,
    default="stdout",
    help=(
        "Destination for console exporter output. Options: stdout or file. "
        "If 'file' is chosen, the output file will be 'otel_traces.jsonl' in the "
        "ECOSCOPE_WORKFLOWS_RESULTS results directory."
    ),
)
def run(
    config_file: Optional[TextIOWrapper],
    config_json: Optional[str],
    execution_mode: str,
    mock_io: bool,
    otel_exporter: Optional[str],
    otel_console_exporter_dst: str,
) -> None:
    import obstore
    import ruamel.yaml
    from wt_contracts import ValidationError, validate
    from wt_task.tracing import (
        attach_context,
        configure_tracer,
        make_otel_console_exporter_file_dst_kws,
    )

    try:
        from opentelemetry import trace

        _HAS_OTEL = True
    except ImportError:
        _HAS_OTEL = False

    from .dispatch import dispatch
    from .metadata import load_params_schema

    # Validate that exactly one of --config-file or --config-json is provided
    if (config_file is not None and config_json is not None) or (
        config_file is None and config_json is None
    ):
        raise click.UsageError(
            "Exactly one of --config-file or --config-json must be provided."
        )

    # Load configuration based on which option is provided
    if config_file is not None:
        yaml = ruamel.yaml.YAML(typ="safe")
        params = yaml.load(config_file) or {}
    else:  # config_json is not None
        try:
            params = json.loads(config_json)
        except json.JSONDecodeError as e:
            raise click.BadParameter(
                "Invalid JSON string for --config-json", param_hint="--config-json"
            ) from e

    params_schema = load_params_schema()
    try:
        validate(params, params_schema)
    except ValidationError as e:
        param_hint = "--config-file" if config_file is not None else "--config-json"
        raise click.BadParameter(
            f"Invalid configuration: {e}", param_hint=param_hint
        ) from e

    results_url = os.environ.get("ECOSCOPE_WORKFLOWS_RESULTS")
    if not results_url:
        raise ValueError("Environment variable ECOSCOPE_WORKFLOWS_RESULTS is required.")
    try:
        _version = version(RELEASE_NAME)
    except PackageNotFoundError:
        _version = "unknown"
    otel_exporter_kws: dict = {}
    if otel_exporter == "console" and otel_console_exporter_dst == "file":
        parsed_results_url = urlparse(results_url)
        if parsed_results_url.scheme != "file":
            raise ValueError(
                "When using --otel-exporter console with --otel-console-exporter-dst file, "
                "ECOSCOPE_WORKFLOWS_RESULTS must be a file URL (file://...)."
            )
        otel_exporter_kws |= make_otel_console_exporter_file_dst_kws(
            target_dir=Path(parsed_results_url.path),
        )
    configure_tracer(
        RELEASE_NAME,
        version=_version,
        exporter=otel_exporter,
        exporter_kws=otel_exporter_kws,
    )
    if (traceparent := os.environ.get("TRACEPARENT")) is not None:
        attach_context(traceparent, tracestate=os.environ.get("TRACESTATE"))
    if _HAS_OTEL:
        tracer = trace.get_tracer(__name__)
        tracer_attributes = {
            "execution_mode": execution_mode,
            "mock_io": mock_io,
            "config.time_range": json.dumps(params.get("time_range", "")),
            "config.groupers": json.dumps(params.get("groupers", "")),
            "version": _version,
        }
        with tracer.start_as_current_span(
            f"{RELEASE_NAME}.cli", attributes=tracer_attributes
        ):
            response = dispatch(
                execution_mode, mock_io, params, validate_params_schema=False
            )
            result_store = obstore.store.from_url(results_url)
            result_bytes = response.model_dump_json().encode("utf-8")
            put_result = result_store.put("result.json", result_bytes)
            if not put_result:
                raise RuntimeError("Failed to put result json in result store.")
    else:
        response = dispatch(
            execution_mode, mock_io, params, validate_params_schema=False
        )
        result_store = obstore.store.from_url(results_url)
        result_bytes = response.model_dump_json().encode("utf-8")
        put_result = result_store.put("result.json", result_bytes)
        if not put_result:
            raise RuntimeError("Failed to put result json in result store.")


@cli.command()
@click.argument(
    "metadata_attribute",
    type=click.Choice(["rjsf", "params", "data-connection-property-names"]),
    required=True,
)
def get(metadata_attribute: str) -> None:
    """Get the metadata for the workflow."""
    from .metadata import (
        get_data_connection_property_names,
        load_params_schema,
        load_rjsf_schema,
    )

    getter = {
        "rjsf": load_rjsf_schema,
        "params": load_params_schema,
        "data-connection-property-names": get_data_connection_property_names,
    }.get(metadata_attribute)
    if getter is None:
        raise ValueError(f"Unknown metadata attribute: {metadata_attribute}")
    result = getter()
    as_json = json.dumps(result)
    print(as_json)


@cli.command()
@click.option(
    "--from",
    "from_",
    required=True,
    type=click.Choice(["params", "formdata"]),
)
@click.option(
    "--to",
    required=True,
    type=click.Choice(["params", "formdata"]),
)
@click.option(
    "--json",
    "json_",
    required=True,
    type=click.File("r"),
    default=sys.stdin,
)
def convert(
    from_: str,
    to: str,
    json_: TextIOWrapper,
) -> None:
    """Convert between params and formdata representations.

    Emits a single-key JSON envelope on stdout:

    - ``{"result": {...}}`` on success
    - ``{"validation_errors": [...]}`` on schema-validation failure

    Exit code is ``0`` for both outcomes; non-zero is reserved for genuine
    CLI failures (bad args, missing schema files, ...).
    """
    from wt_contracts import (
        ValidationError,
        formdata_to_params,
        params_to_formdata,
    )

    from .metadata import load_params_schema, load_rjsf_schema

    json_txt = json_.read()
    try:
        loaded = json.loads(json_txt)
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse JSON string: {json_txt}") from e

    rjsf_schema = load_rjsf_schema()
    params_schema = load_params_schema()
    try:
        match from_, to:
            case ("params", "formdata"):
                result = params_to_formdata(loaded, rjsf_schema, params_schema)
            case ("formdata", "params"):
                result = formdata_to_params(loaded, rjsf_schema, params_schema)
            case _:
                raise ValueError(f"Unknown conversion: {from_} -> {to}")
        envelope: dict[str, Any] = {"result": result}
    except ValidationError as e:
        envelope = {"validation_errors": e.errors}

    print(json.dumps(envelope))


if __name__ == "__main__":
    cli()
