# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


import traceback
from typing import Any

from .response import ResponseModel


def dispatch(
    execution_mode: str,  # TODO: literal type
    mock_io: bool,
    params: dict[str, Any],
    validate_params_schema: bool = True,
) -> ResponseModel:
    match execution_mode, mock_io:
        case ("sequential", True):
            from .dags.run_sequential_mock_io import main as dispatcher

        case ("sequential", False):
            from .dags.run_sequential import main as dispatcher

        case _:
            raise ValueError(f"Invalid execution mode: {execution_mode}")

    try:
        result = dispatcher(
            params=params, validate_params_schema=validate_params_schema
        )
        response = ResponseModel(result=result)
        response.model_dump_json()  # eagerly validate JSON-serializability
    except Exception as e:
        trace = traceback.format_exc()
        response = ResponseModel(error=str(e), trace=trace)

    return response
