# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


import json
from importlib.resources import files
from typing import Any

from wt_contracts import (
    formdata_to_params as _formdata_to_params,
)
from wt_contracts import (
    params_to_formdata as _params_to_formdata,
)


def load_rjsf_schema() -> dict[str, Any]:
    """Load the RJSF (grouped) JSON schema bundled with this package."""
    with files(__package__).joinpath("rjsf.json").open() as f:
        result: dict[str, Any] = json.load(f)
        return result


def load_params_schema() -> dict[str, Any]:
    """Load the flat params JSON schema bundled with this package."""
    with files(__package__).joinpath("params.json").open() as f:
        result: dict[str, Any] = json.load(f)
        return result


def get_data_connection_property_names() -> dict[str, list[str]]:
    params = load_params_schema()
    data_connections: dict[str, list[str]] = {}
    for k, v in params["properties"].items():
        if isinstance(v, dict) and v.get("properties"):
            for inner_k, inner_v in v["properties"].items():
                if isinstance(inner_v, dict) and inner_v.get("$ref"):
                    ref = inner_v.get("$ref")
                    if ref.endswith("Connection"):
                        key = (
                            inner_v.get("$ref").lstrip("#/$defs/").rstrip("Connection")
                        )
                        if data_connections.get(key):
                            data_connections[key].append(k)
                        else:
                            data_connections[key] = [k]
    return data_connections


def formdata_to_params(formdata: dict[str, Any]) -> dict[str, Any]:
    return _formdata_to_params(formdata, load_rjsf_schema(), load_params_schema())


def params_to_formdata(params: dict[str, Any]) -> dict[str, Any]:
    return _params_to_formdata(params, load_rjsf_schema(), load_params_schema())
