# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from typing import Any

from pydantic import BaseModel


class ResponseModel(BaseModel):
    result: Any = None
    error: str | None = None
    trace: str | None = None
